### ISSUE TITLE
运行train.py老是出问题。。ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by DOCTOROLIVE** [sorting4peach/sorting4peach#7]
File "/home/doctorolive/anaconda2/lib/python2.7/site-packages/paddle/v2/trainer.py", line 220, in test
    evaluator=evaluator, cost=total_cost / num_samples)
ZeroDivisionError: float division by zero

**Comment by DOCTOROLIVE** [comment]
这个该如何解决呀，谢谢

**Comment by breaknormal1** [comment]
@DOCTOROLIVE @zzx2GH 
hi，老兄
解决了吗？我也遇到了相同的问题？有没有思路？

**Comment by DOCTOROLIVE** [comment]
已经解决，这是找不到训练图片。所以num_samples=0，你建立一个文件夹，命名为train ，train下面有4个文件夹，class0,class1,class2,class3.     class0下有一个文件夹命名为0，第一类训练图片放在这里，class1下有个1，class2下有个2，class3下有个3 。   test 文件夹 以此类推

**Comment by DOCTOROLIVE** [comment]
@breaknormal1

**Comment by breaknormal1** [comment]
@DOCTOROLIVE 谢谢，用你的方法解决了
